root: ./

redirects:
    apps-development/uikit: apps-engine/adding-features/uikit/README.md
    apps-engine/rocket.chat-apps-engine: apps-engine/rocket.chat-apps-and-apps-engine.md
    apps-engine/testing-your-app: apps-engine/rocket.chat-apps-and-apps-engine.md
    apps-engine/slack-compatibility: apps-engine/rocket.chat-apps-and-apps-engine.md
